version: '3'

services:
  app:
    build:
      context: ./docker/php
    container_name: ${APP_NAME:-docklar_app}_app
    volumes:
      - ./:/var/www/html
    depends_on:
      - redis
      - database
    networks:
      - docklar

  server:
    image: nginx:stable-alpine
    container_name: ${APP_NAME:-docklar}_webserver
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
      - ./docker/logs/nginx:/var/logs/nnginx:rw
    depends_on:
      - app
    networks:
      - docklar

  database:
    image: 'mysql:8.0'
    restart: unless-stopped
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - docklar

  redis:
    container_name: ${APP_NAME:-docklar}_redis
    image: redis:latest
    ports:
      - ${REDIS_PORT:-6379}:6379
    networks:
      - docklar

networks:
  docklar:
    driver: bridge
volumes:
  dbdata:
    driver: local
