version: '3'
services:

  webapp:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: webapp
    restart: unless-stopped
    tty: true
    environment:
      REDIS_HOST: redis
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    # command: composer install --no-scripts --no-autoloader -n
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/logservice.ini
    networks:
      - docklar-network

  webserver:
    image: nginx:alpine
    restart: always
    tty: true
    ports:
      - '${APP_PORT:-8094}:80'
      - "450:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf:rw
    networks:
      - docklar-network

  db:
    image: mysql:8.0
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - ${FORWARD_DB_PORT:-3306}:3306
    networks:
      - docklar-network

  pma:
    image: phpmyadmin:5.1
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
      - PMA_PORT=${DB_PORT}
    depends_on:
      - db
    ports:
      - 8854:80
    networks:
      - docklar-network

  redis:
    image: 'redis:latest'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    networks:
      - docklar-network
    depends_on:
      - webapp
  supervisor:
    build:
      context: ./docker/supervisor
      dockerfile: Dockerfile
    container_name: supervisor
    volumes:
      - ./:/var/www/html
    networks:
      - docklar-network

networks:
  docklar-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
